# My first python project - A Simple Resume
print("========================================\n")
print("\t", "\t", "My Resume", "\t", "\t", "\t \n")
print("========================================\n\n")
print("Name", "\t", "\t", ":" "Joe Sunny Kondala")
print("Profession", "\t", ":" "Voice and Accent Trainer")
print("Experience", "\t", ":" "!0 Years\n\n")
print("Technical Skills" ":\n")
print(" ", " ", "Python")
print(" ", " ", "SQL")
print(" ", " ", "Excel\n\n")
print("Career Goal" ":\n")
print(" ", " ", "Become a Fullstack Developer\n")
print("========================================")
